### ISSUE TITLE
Node does not automatically restart when stopped

### ISSUE THREAD

**Issue by sangtn0102** [rykcod/massa#12]
Hello, my node is stopped, but it is not restarted automatically, the node log file is like the picture, how to fix it?
![image](https://user-images.githubusercontent.com/107299476/197367493-6a6edac1-0259-42e7-b690-217b15361eba.png)

**Comment by rykcod** [comment]
You are the second person with this issue, i will recheck the script condition will back on your issue. Thanks

**Comment by rykcod** [comment]
Issue solve,
This issue since echo for "docker logs" integration,
And no really ticket because the ep15 was really stable ^^
Fixed now on the last release,
Thanks
