### ISSUE TITLE
/massa-guard/massa-guard.sh: line 49: [: -eq: unary operator expected

### ISSUE THREAD

**Issue by 0xpoolboy** [rykcod/massa#18]
There seems to be a bug in massa-guard.sh.

I am  running the node with Logs enabled (default).
The following line is spammed into logs when running: ```docker logs massa-node -f````

```
/massa-guard/massa-guard.sh: line 49: [: -eq: unary operator expected
/massa-guard/massa-guard.sh: line 49: [: -eq: unary operator expected
/massa-guard/massa-guard.sh: line 49: [: -eq: unary operator expected
/massa-guard/massa-guard.sh: line 49: [: -eq: unary operator expected
/massa-guard/massa-guard.sh: line 49: [: -eq: unary operator expected
/massa-guard/massa-guard.sh: line 49: [: -eq: unary operator expected
```

**Comment by rykcod** [comment]
Hello guy,
Please just follow README for the last release:
20230616 - Testnet 23 - v23.2.0 - Testnet 23 - Add disable logs Feature with NODE_LOGS settings.

In fact you need to add a new propertie into your config.ini file if your keep your last,
Set your ''NODE_LOGS'' value to disable logs files (0=Disable 1=Enable). Default value 1.
